#!/bin/bash

if [ -z "$1" ]; then
    venv_name="${USER}-groundhog-env"
else
    venv_name="$1"
fi

python3 -m venv $venv_name

source "$venv_name/bin/activate"

pip install -U pip setuptools
pip install -r requirements.txt
pip install .
