#!/bin/bash

if [ -z "$1" ]; then
    venv_name="${USER}-groundhog-env"
else
    venv_name="$1"
fi

python3 -m venv $venv_name

source "$venv_name/bin/activate"

python3 -m pip install setuptools
python3 -m pip install wheel
python3 -m pip install -r requirements.txt
python3 -m pip install .
